### ISSUE TITLE
Page not showing Capes when LabyMod returns invalid data

### ISSUE THREAD

**Issue by SpraxDev** [InventivetalentDev/api.capes.dev#2]
## What steps will reproduce the problem?  
1. Search for the user `ade2252606124a36a183eefeed1d8f02`
2. Wait for eternity for stuff to load :p

## What were you expecting to happen? What happened instead?
Requesting the LabyMod cape for this user caused an `Error: Input buffer contains unsupported image format` on my end (my own API). So I got curious how capes.dev handles this.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
No plugin.

## What Spigot version are you using? *Type /version*  
No Server.

## What plugins are you using? *Type /plugins*  
No Server.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
`GET https://api.capes.dev/load/ade2252606124a36a183eefeed1d8f02 [HTTP/2 502 Bad Gateway 90163ms]`

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*
No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
LabyMod returns a 0 bytes body for this users cape, instead of responding as it would be expected for users without a skin.

**Comment by InventivetalentDev** [comment]
Yeah looks like they're returning 200 with 0-length content which breaks stuff. Should be an easy fix :)
